title: MS20
date: 2025-12-26
lang: fr
author: Site réalisé par Martin.
email: j.metzler@vauban.lu
description: >-
  Le Makerspace n°20 du Luxembourg, un espace de création, d'innovation et de partage
baseurl: ""
url: "https://ms20.lu"
instagram_username: ms20.vauban
github_username: m-krem
school: "Vauban, École et Lycée français de Luxembourg"
school_url: "https://vauban.lu"

theme: minima
plugins:
  - jekyll-feed

collections:
  events:
    output: true
    permalink: /events/:name/
  members:
    output: true
    permalink: /members/:name/
  projects:
    output: true
    permalink: /projects/:name/